version: '3.9'

services:
  service:
    user: node
    build:
      context: ./service
      target: development
    depends_on:
      - redis
    environment:
      REDIS_URL: 'redis://redis:6379/1'
    volumes:
      - ./service:/app
      - service_dist:/app/dist:rw
    networks:
      plinq-network:
        aliases:
          - plinq
  redis:
    image: redis:7-alpine
    networks:
      plinq-network:
        aliases:
          - redis
  moodle:
    image: bitnami/moodle:4
    depends_on:
      - mariadb
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MOODLE_DATABASE_USER:     bn_moodle
      MOODLE_DATABASE_PASSWORD: bitnami
      MOODLE_DATABASE_NAME:     bitnami_moodle
      MOODLE_DATABASE_HOST:     moodle-db
    volumes:
      - moodle_data:/bitnami/moodle
      - ./plinq:/bitnami/moodle/mod/assign/feedback/plinq
    networks:
      moodle-network:
        aliases:
          - moodle
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_USER:     bn_moodle
      MARIADB_PASSWORD: bitnami
      MARIADB_DATABASE: bitnami_moodle
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATE:       utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      moodle-network:
        aliases:
          - moodle-db
  rcli:
    image: redis:6-alpine
    command: redis-cli -h redis
    networks:
      plinq-network:
    profiles:
      - tools

networks:
  plinq-network:
    driver: bridge
  moodle-network:
    driver: bridge

volumes:
  service_dist:
  moodle_data:
  mariadb_data:
